config/routes.rb
Usherette::Application.routes.draw do
  resources :messages, :only => [:new, :create]
  devise_for :users

    root :to => 'performances#index'
  resources :performances
  resources :venues
  resources :shows
  resources :tickets
  resources :carts
  resources :payment_notifications
  match 'shows/:id/will_call' => 'shows#will_call', :as => 'will_call'
  match 'shows/:id/reserve' => 'shows#reserve', :as => 'reserve'
  match 'about' => 'messages#about'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many :tickets
    has_one :payment_notification
    attr_accessible :purchased_at, :placed_at, :order_firstname, :order_lastname, :order_email, :payment_type
    validates_presence_of :order_firstname, :if => :placed_at? 
    validates_presence_of :order_lastname, :if => :placed_at?
    validates_presence_of :payment_type, :if => :placed_at?
    validate :tickets_still_available?, :if => :placed_at?
    as_enum :payment_type, :paypal => 0, :door => 1, :check => 2, :cash => 3

    def add_ticket(perf_id, quantity)
        performance = Performance.find(perf_id)
        if performance and not performance.sold_out?
            ticket = Ticket.find_by_cart_id_and_performance_id(self.id, perf_id)
            if ticket
                ticket.quantity += quantity.to_i
            else
                ticket = Ticket.new(performance_id: perf_id, cart_id: self.id, quantity: quantity)
            end
            return ticket
        else
            return nil
        end
    end
    def paypal_url(return_url, notify_url)
        values = {
            :business => APP_CONFIG[:paypal_email],
            :cmd => '_cart',
            :upload => 1,
            :return => return_url,
            :invoice => id,
            :notify_url => notify_url
        }

        tickets.each_with_index do |item, index|
            values.merge!({
                "amount_#{index + 1}" => to_price_string(item.performance.price * item.quantity),
                "item_name_#{index + 1}" => item.performance.show.title,
                "item_number_#{index + 1}" => item.performance.id,
                "quantity_#{index + 1}" => 1
            })
        end
        "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
    end

    def paypal_encrypted_url(return_url, notify_url)
        values = {
            :business => APP_CONFIG[:paypal_email],
            :cmd => '_cart',
            :upload => 1,
            :return => return_url,
            :invoice => id,
            :notify_url => notify_url,
            :cert_id => APP_CONFIG[:paypal_cert_id]
        }

        tickets.each_with_index do |item, index|
            values.merge!({
                "amount_#{index + 1}" => to_price_string(item.performance.price),
                "item_name_#{index + 1}" => "#{item.performance.show.title} #{item.performance.date_string}",
                "item_number_#{index + 1}" => item.performance.id,
                "quantity_#{index + 1}" => item.quantity
            })
        end
        return  encrypt_for_paypal(values)
    end
    private

    PAYPAL_CERT_PEM = File.read("#{Rails.root}/certs/paypal_cert.pem")
    APP_CERT_PEM = File.read("#{Rails.root}/certs/app_cert.pem")
    APP_KEY_PEM = File.read("#{Rails.root}/certs/app_key.pem")

    def encrypt_for_paypal(values)
        signed = OpenSSL::PKCS7::sign(OpenSSL::X509::Certificate.new(APP_CERT_PEM),
                                      OpenSSL::PKey::RSA.new(APP_KEY_PEM, ''), 
                                      values.map { |k, v| "#{k}=#{v}" }.join("\n"), 
                                      [], 
                                      OpenSSL::PKCS7::BINARY)
        OpenSSL::PKCS7::encrypt(
            [OpenSSL::X509::Certificate.new(PAYPAL_CERT_PEM)], 
            signed.to_der, 
            OpenSSL::Cipher::Cipher::new("DES3"),
            OpenSSL::PKCS7::BINARY).to_s.gsub("\n", "")
    end

    def tickets_still_available?
        self.tickets.each do |t| 
            if not t.still_available?
                errors.add(:base, "One or more of the shows in your cart is sold out.")
                return false
            end
        end
        return true
    end

    def to_price_string(price)
        return "%d.%d" % [price / 100, price % 100]
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_filter :authenticate_user!, :only => [:create]
    def create
        @cart = Cart.new(params['cart'])
        @show = Show.find(params['show_id'])
        @cart.placed_at = Date.today
        if not @cart.save
            render 'shows/reserve' and return
        else
            params['perf'].each_with_index do |perf, i|
                if params['qty'][i].to_i > 0 
                    @cart.add_ticket(perf,params['qty'][i]).save
                end
            end
            @cart.purchased_at = Date.today
            if not @cart.save
                render 'shows/reserve'
            else
                @cart.reload
            end
        end
    end

    def show
        @cart = @current_cart
    end

    def edit
    end

    def update
        if @current_cart.update_attributes(params[:cart].merge(:placed_at => Time.now()))
            @current_cart.save
            @encrypted = @current_cart.paypal_encrypted_url(performances_url, payment_notifications_url)
        else
            render :edit
        end
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_shipping.html.erb
<% if need_to_mail.length > 0 %>
    <div class='note'>
    <span>Note:</span> 
    The following items will need to be mailed to you.  
    Please confirm your shipping details via PayPal.
    <ul>
        <% need_to_mail.each do |p| %>
            <li><%= p.show.title %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/carts/create.html.erb
<p>Order placed for <%= @cart.order_firstname %> <%= @cart.order_lastname %>
</p>
<p>A sumary of the order is below </p>
<table>
    <tr><td>Show</td><td>Quantity</td></tr>
    <% @cart.tickets.each do |t| %>
        <tr>
        <td><%= t.performance.date_string  %> </td>
        <td><%= t.quantity %></td>
    </tr>
<% end %>
</table>

app/views/carts/edit.html.erb
<% content_for :title, "Shopping Cart" %>
<% need_to_mail = []%>
<%= form_for @current_cart do |f|%>
  <% if @current_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@current_cart.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @current_cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h2>Order Summary</h2>
    <table class='order_summary' >
        <tr>
            <th>&nbsp;</th>
            <th>When</th>
            <th>What</th>
            <th>Price</th>
            <th>Quantity</th>
        </tr>
    <% @current_cart.tickets.each do |t| %>
        <tr>
            <td><%= link_to "", ticket_path(t), :method => :delete, :title => 'Remove from cart', :class=>'icon-remove' %></td>
            <td><%= t.performance.date_string %></td>
            <td><%= t.performance.show.title %></td>
            <td><%= t.performance.price_string %></td>
            <td><%= t.quantity %> <% if not t.still_available? %> <b>Sold Out</b><% end %></td>
        </tr>
        <% if t.performance.mail? %>
            <% need_to_mail << t.performance %>
        <% end %>
    <% end %>
</table>
    <p> Unless otherwise noted, your tickets will be held for you at the door under the name
    provided below.</p>
    <div class='field'>
        <%= f.label :order_firstname, 'First Name'%>
        <%= f.text_field :order_firstname %>
    </div>
    <div class='field'>
        <%= f.label :order_lastname, 'Last Name'%>
        <%= f.text_field :order_lastname %>
    </div>
    <%= render :partial=>'shipping', :locals=> {:need_to_mail => need_to_mail} %>
    <div class='field'>
        <%= f.submit 'Checkout with PayPal' %>
    </div>
<% end  %>

app/views/carts/new.html.erb
<h1><%= @show.title %></h1>
<%= form_for @cart do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= hidden_field_tag :show_id, @show.id %>
    <div class='field'>
    <%= f.label :order_firstname, 'First Name'%>
    <%= f.text_field :order_firstname %>
</div>
<div class='field'>
    <%= f.label :order_lastname, 'Last Name'%>
    <%= f.text_field :order_lastname %>
</div>
<table>
    <tr>
        <td>Performance</td>
        <td>Quantity</td>
    </tr>
    <% @show.performances.each do |p| %>
        <tr>
        <td><%= p.date_string %></td>
        <td><%= hidden_field_tag "perf[]", p.id %>
        <%= select_tag "qty[]", options_for_select((0..20).to_a) %> </td>
</tr>
<% end %>
</table>
<div class='field'>
    <%= f.label :payment_type %>
    <%= f.select :payment_type, Cart.payment_types.keys, :include_blank => true %>
    <div>
<div class='field'>
    <%= f.submit 'Submit' %>
</div>
<% end %>

app/views/carts/show.html.erb
<table border=1>
    <% @cart.tickets.each do |t| %>
        <tr>
            <td><%= t.performance.date_string %></td>
            <td><%= t.performance.show.title %></td>
            <td><%= t.performance.price_string %></td>
        </tr>
    <% end %>
</table>
<%= link_to 'Begin Checkout', edit_cart_path(@current_cart) %>
<%= link_to "Checkout", @current_cart.paypal_url(performances_url, payment_notifications_url) %>

app/views/carts/update.html.erb
<p>Please wait...</p>
<%= form_tag APP_CONFIG[:paypal_url] do  %>
    <%= hidden_field_tag 'cmd', '_s-xclick' %>
    <%= hidden_field_tag 'encrypted', @encrypted %>
<% end %>
<script>
    document.forms[0].submit();
</script>