config/routes.rb
Usherette::Application.routes.draw do
  resources :messages, :only => [:new, :create]
  devise_for :users

    root :to => 'performances#index'
  resources :performances
  resources :venues
  resources :shows
  resources :tickets
  resources :carts
  resources :payment_notifications
  match 'shows/:id/will_call' => 'shows#will_call', :as => 'will_call'
  match 'shows/:id/reserve' => 'shows#reserve', :as => 'reserve'
  match 'about' => 'messages#about'
end

app/models/show.rb
class Show < ActiveRecord::Base
    has_many :performances
    attr_accessible :description, :title, :banner, :logo
    validates_presence_of :title
    validates_presence_of :description
    has_attached_file :banner, :styles => { :medium => "960x240>"}, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :banner, :content_type => /\Aimage\/.*\Z/
    has_attached_file :logo, :styles => { :medium => "480x240>"}, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :banner, :content_type => /\Aimage\/.*\Z/

    def to_param
        "#{id}-#{title}".parameterize
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]
  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.order(:id).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shows }
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    @show = Show.find(params[:id])
    @performances = @show.performances.order('date')
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/new
  # GET /shows/new.json
  def new
    @show = Show.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/1/edit
  def edit
    @show = Show.find(params[:id])
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(params[:show])

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render json: @show, status: :created, location: @show }
      else
        format.html { render action: "new" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shows/1
  # PUT /shows/1.json
  def update
    @show = Show.find(params[:id])

    respond_to do |format|
      if @show.update_attributes(params[:show])
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show = Show.find(params[:id])
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url }
      format.json { head :no_content }
    end
  end

  def will_call
      @show = Show.find(params[:id])
      @sort = params[:sort] ? params[:sort] : 'purchased_at'
      @performances = @show.performances.order('date')
      @performance_tickets = @performances.map.with_index do |p, idx|
          p.tickets.includes(:cart).where('carts.purchased_at is not null').order("carts.#{@sort}")
      end
  end

  def reserve
      @cart = Cart.new
      @show = Show.find(params[:id])
      @performances = @show.performances.order('date')
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_address.html.erb
<% if payment_notification %>
    <%= payment_notification.params['address_name'] %><br />
    <%= payment_notification.params['address_street'] %><br />
    <%= payment_notification.params['address_city'] %>,
    <%= payment_notification.params['address_state'] %>
    <%= payment_notification.params['address_zip'] %>
<% end %>

app/views/shows/_form.html.erb
<%= form_for(@show, :html => { :multipart => true }) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
      <%= f.label :banner %></br />
      <%= f.file_field :banner %>
  </div>
  <div class="field">
      <%= f.label :logo %></br />
      <%= f.file_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing show</h1>

<%= render 'form' %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<h1>Admin Panel</h1>
<%= link_to new_show_path, :class=>'add_btn'  do %>
    <i class='icon-plus'></i> Add New Show
<% end %>

<div class='list'>
    <% @shows.each do |show| %>
        <div class='listing'>
            <h2><%= show.title %></h2>
            <span class='actions'>
                <%= link_to 'View', show %> | 
                <%= link_to 'Edit', edit_show_path(show) %> |
                <%= link_to 'Will-Call List', will_call_path(show) %> |
                <%= link_to 'Add Reservation', reserve_path(show) %></td>
            </span>
        </div>
    <% end %>
</div>

app/views/shows/new.html.erb
<h1>New show</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/reserve.html.erb
<h1><%= @show.title %></h1>
<%= form_for @cart do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= hidden_field_tag :show_id, @show.id %>
    <div class='field'>
    <%= f.label :order_firstname, 'First Name'%>
    <%= f.text_field :order_firstname %>
</div>
<div class='field'>
    <%= f.label :order_lastname, 'Last Name'%>
    <%= f.text_field :order_lastname %>
</div>
<table>
    <tr>
        <td>Performance</td>
        <td>Quantity</td>
    </tr>
    <% @performances.each do |p| %>
        <tr>
        <td><%= p.date_string %></td>
        <td><%= hidden_field_tag "perf[]", p.id %>
        <%= select_tag "qty[]", options_for_select((0..20).to_a) %> </td>
</tr>
<% end %>
</table>
<div class='field'>
    <%= f.label :payment_type %>
    <%= f.select :payment_type, Cart.payment_types.keys, {:include_blank => true, :selected => nil} %>
    <div>
<div class='field'>
    <%= f.submit 'Submit' %>
</div>
<% end %>

app/views/shows/show.html.erb
<% content_for :title, @show.title %>
<% if @show.banner? %>
        <%= image_tag @show.banner.url(:medium), :class=>'banner' %>
<% end %>
<p id="notice"><%= notice %></p>
<% if @show.logo? %>
    <%= image_tag @show.logo.url(:medium), :class=>'show-logo', :alt => @show.title %>
<% else %>
    <h2><%= @show.title %></h2>
<% end %>
<div class='clear'></div>
<div class='column left'>
    <div class='show-descrition'> <%= simple_format(@show.description) %> </div>
  </div>
  <div class='column right'>

<h3>Performances:</h3>
<div class='list'>
    <% @performances.each do |performance| %>
        <div class='listing'>
            <p><b><%= performance.venue.name %></b><br />
                <%= link_to "#{performance.date_string}", performance_path(performance) %></p> 
                <%= link_to_if(user_signed_in?, "Edit", edit_performance_path(performance)){}%>
        </div>
    <% end %>
    <% if user_signed_in? %>
        <%= link_to new_performance_path(show_id: @show.id), :class=>'add_btn' do %>
        <i class='icon-plus'></i> New Performance
        <% end %>
        <%= link_to edit_show_path(@show), :class=>'add_btn' do  %>
            <i class='icon-edit'></i> Edit Curent Show
        <% end %>
<% end %>
</div>
</div>

app/views/shows/will_call.html.erb
<% content_for :title, "#{@show.title} Reservations" %>
<style>
</style>
<h2>Will Call - <%= @show.title %></h2>

<% if params[:print] != "1" %>
    <%= link_to will_call_path(@show, :print=>1, :sort=>'order_lastname') do %>
        <i class='icon-print'></i> Print
    <% end %>
<% else %>
    <%= link_to will_call_path(@show) do %>
        <i class='icon-print'></i> Don't Print
    <% end %>
<% end %>
<table class='fancy' cellpadding=0 cellspacing=0 width='100%' >
    <thead>
        <tr>
            <td>
                <%= link_to will_call_path(@show, :sort=>'purchased_at') do %>
                    Time <i class='icon-sort-by-order'></i>
                <% end %>
            </td>
            <td> 
                <%= link_to will_call_path(@show, :sort=>'order_firstname') do %>
                    First <i class='icon-sort-by-alphabet'></i>
                <% end %>
            </td>
            <td>
                <%= link_to will_call_path(@show, :sort=>'order_lastname') do %>
                    Last <i class='icon-sort-by-alphabet'></i>
                <% end %>
            </td>
            <td>
                <%= link_to will_call_path(@show, :sort=>'order_email') do %>
                    Email <i class='icon-sort-by-alphabet'></i>
                <% end %>
             </td>
                <td>Qty.</td>
                <td><%= link_to will_call_path(@show, :sort=>'payment_type_cd') do %>
                    Type <i class='icon-sort-by-alphabet'></i>
                <% end %></td>
            </tr>
        </thead>
        <% total = 0 %>
        <% @performances.each_with_index do |p, idx| 
            perf_total = 0 %>
        <tr>
            <td colspan='6' class='dark'><%= p.date_string %></td>
            <% @performance_tickets[idx].each do |t| %>
                <% if t.cart.purchased_at? %>
                    <tr class='<%= cycle('even','odd') %>'>
                        <td><%= t.cart.placed_at.localtime %></td>
                        <td><%= t.cart.order_firstname %> </td>
                        <td><%= t.cart.order_lastname %></td>
                        <td><%= t.cart.order_email %></td>
                        <td><%= t.quantity %> <%="☐ " * t.quantity if params[:print] == "1"%></td>
                        <td><%= t.cart.payment_type %></td>
                        <% total += t.quantity %>
                        <% perf_total += t.quantity %>
                    </tr>
                <% end %>
            <% end %>
                <tr class='minor_total'>
                <td colspan='5'><%= p.date_string %> Total</td>
                <td><%= perf_total %></td>
            </tr>
        </tr>
    <% end %>
        <tr class='total'>
            <td colspan='5'>Show Total</td>
            <td><%= total %></td>
        </tr>
    </table>