config/routes.rb
Usherette::Application.routes.draw do
  resources :messages, :only => [:new, :create]
  devise_for :users

    root :to => 'performances#index'
  resources :performances
  resources :venues
  resources :shows
  resources :tickets
  resources :carts
  resources :payment_notifications
  match 'shows/:id/will_call' => 'shows#will_call', :as => 'will_call'
  match 'shows/:id/reserve' => 'shows#reserve', :as => 'reserve'
  match 'about' => 'messages#about'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
    <title>Usherette - <%= yield(:title) %></title>
        <%= stylesheet_link_tag    "application", :media => "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
        <link href='//fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
        <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
        <meta name=viewport content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class='header'>
            <div class='container'>
                <h1 style=''><%= link_to "Usherette", root_path %></h1>
                <div class='shopping-cart'>
                    <i class='icon-shopping-cart'></i> <%= link_to "My Cart (#{@current_cart.tickets.size})", edit_cart_path(@current_cart) %>
            </div>
                <% if user_signed_in? %>
                    <div class='logout'>
                        Logged in as <%= current_user.firstname %> | 
                    <%= link_to shows_path() do %>
                        <i class='icon-edit'></i> Admin Panel
                    <% end %> | 
                    <%= link_to destroy_user_session_path, :method=>:delete do %>
                        <i class='icon-signout'></i> Logout
                    <% end %>
                    </div>
                <% end %>
                <div style='clear: both'></div>
            </div>
        </div>
        <% flash.each do |key, value| %>
              <%= content_tag(:div, value, :class => "notice #{key}") %>
          <% end %>
        <div class='container'>
            <%= yield %>
        </div>
        <div class='footer clearfix'>
            <%= link_to 'Contact', new_message_path() %> |
            <a href='/about'>About</a>
            <br />
            Copyright &copy; 2013 - Frank Riccobono
        </div>
        <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-44059036-1', 'hopeforchange.org');
    ga('send', 'pageview');

        </script>
    </body>
</html>